import React from 'react';
import RaisedButton from 'material-ui/lib/raised-button';
import { Router, Route, Link } from 'react-router';
import CardText from 'material-ui/lib/card/card-text';
import CardHeader from 'material-ui/lib/card/card-header';
import CardTitle from 'material-ui/lib/card/card-title';
import TextField from 'material-ui/lib/text-field';
import DescriptionStore from '../stores/description';
import DescriptionActions from '../actions/descriptionActions';
const CardActions = require('material-ui/lib/card/card-actions');

const containerStyle = {
};
const textStyle = {
  textAlign: 'left',
  width: '700px',
  display:'block'
};

const FisheryDescription = React.createClass({

  calculateState() {
    return {
      fishery: DescriptionStore.getFishery(),
      stakeholders: DescriptionStore.getStakeholders()
    }
  },

  getInitialState() {
    let state = this.calculateState();
    return state;
  },

  componentDidMount() {

  },

  componentWillUnmount() {

  },

  _handleFisheryChange(event){
    return (function(event) {
      let fishery = this.refs.fisheryTextField.getValue();
      DescriptionActions.setFishery(fishery);
    }).bind(this);
    
  },

  _handleStakeholderChange(event){
    return (function(event) {
      let stakeholders = this.refs.stakeholdersTextField.getValue();
      DescriptionActions.setStakeholders(stakeholders);
    }).bind(this);
    
  },

  _handlePrev() {
    this.props.history.push(...this.props.location, "/intro");
  },

  _handleNext() {
    this.props.history.push(...this.props.location, "/goal_overview");
  },

  render() {
    return (

      <div>
        <CardTitle
          title="Fishery Description"
          avatar={<div />} />
        <CardText expandable={true}>
        <div style={{textAlign:'left'}}>
          <p>
            What is the fishery and stakeholder group(s) being considered in this analysis? <br/><br/>Note: this
            information is for your use only, and will be displayed in the reports generated by this Decision 
            Support Tool.
          </p>
          <TextField style={textStyle} onChange={this._handleFisheryChange()} ref="fisheryTextField" floatingLabelText="Fishery Name" defaultValue={DescriptionStore.getFishery()}></TextField>
          <TextField style={textStyle} onChange={this._handleStakeholderChange()} ref="stakeholdersTextField"  floatingLabelText="Stakeholders" defaultValue={DescriptionStore.getStakeholders()}></TextField>
        </div>
        </CardText>
        <CardActions>
        <RaisedButton label="Back to Intro" onTouchTap={this._handlePrev} />
        <RaisedButton label="Go to Goals Overview" primary={true} onTouchTap={this._handleNext} />
        </CardActions>
      </div>
    );
  },
});

export default FisheryDescription;
